Ext.define('AppProveedores.model.ModeloProveedores', {
    extend: 'Ext.data.Model',
    fields: [
        'COMPANIA',
        'ID_CLIENTE',
        'ORIGEN',
        'NOMBRE',
        'RFC',
        'ACT_ECONOMICA',
        'F_ALTA',
        'RAZON_SOCIAL',
        'PAPELERIA',
        'T_PERSONA',
        'T_CLIEPROV',
        'T_TERCERO',
        'T_OPERACION',
        'ID_FISCAL',
        'NOMBRE_EXTRANJERO',
        'PAIS_RESIDENCIA',
        'NACIONALIDAD',
        'AUXILIAR',
        'CTO_CTO',
        'TIPO_INGRESO',
        'CUENTA',
        'CUENTA_IVA',
        'CORREO' ,
        'TELEFONO',
        'TIPO_POLIZA',
        'BANCO', 
        'NUMERO_CUENTA', 
        'CUENTA_CLAVE',
        'BANCO_PAGO',
        'DIAS_CREDITO',
        'CALLE', 
        'NO_EXTERIOR', 
        'NO_INTERIOR', 
        'COLONIA', 
        'ESTADO', 
        'PAIS',
        'CP',
        'DELEGACION',
        'ESTATUS',
        'MGS_ERR',
        'PASSWORD',
        'CONCEPTO_DEFAULT',
        'VIATICO',
        'CIE',
        'PAGO_CIE',
        'REFERENCIA_CIE',
        'T_OPERACION_DIOT',
        'CUENTA_GASTO',
        'CUENTA_COMPLEMENTARIA',
        'CUENTA_IVA_PAGO',
        'CTO_CTO_DEFAULT',
        'TIPO_CUENTA',
        'SWIFT',
        'IBAN',
        'CUENTA_VALIDA'
    ]


});

