Ext.define('AppCargaFE2.model.ModeloArchivos', {
    extend: 'Ext.data.Model',
    fields: [
        'COMPANIA',
        'NUMERO',
        'FOLIO',
        'UUID',
        'PDF',
        'IVA',
        //'GNOMBRE',
        'FOLIO_FISCAL_ORIG',
        'FECHA',
        'FECHA_FOLIO_FISCAL_ORIG',
        'SERIE',
        'SERIE_FOLIO_FISCAL_ORIG',
        'SUBTOTAL',
        'TOTAL',
        'TIPO_CAMBIO',
        'TIPO_DE_COMPROBANTE',
        'CONDICIONES_DE_PAGO',
        'DESCUENTO',
        'FORMA_DE_PAGO',
        'METODO_DE_PAGO',
        'MONEDA',
        'MONTO_FOLIO_FISCAL_ORIG',
        'LUGAR_EXPEDICION',
        'MOTIVO_DESCUENTO',
        'NO_CERTIFICADO',
        'NUM_CTA_PAGO',
        'NO_CASO',
        'SELLO',
        'VERSION',
        'CERTIFICADO',
        'IDCONCGASTO',
        'NOMIDCONCGASTO',
        'ORIGEN',
        'TIPO_POLIZA',
        'NUMERO_POL',
        'FECHA_POL',
        'XML',
        'FECHA_CAP',       
        'DESCRIPCION',
        'RFC_EMISOR',
        'RFC_RECEPTOR',
        'NOMBRE_EMISOR',
        'NOMBRE_RECEPTOR',
        'FLAG_POLIZA',
        'RFC_COMPANIA',
        'TIPO_CXP',
        'TIPO_GASTO',
        'BENEFICIARIO',
        'OTROS_IMPUESTOS',
        'RFC_COMPANIA',
        'TIPO',
        'CUENTA_CONTABLE',
        'AUXILIAR_CONTABLE',
        'ESTATUSV'

    ]


});

