Ext.define('AppCXPFacturas.model.ModeloIntercos', {
    extend: 'Ext.data.Model',
    fields: [
        'COMPANIA',
        'NUMERO',
        'FOLIO',
        'UUID',
        'PDF',
        'IVA',
        'CXP_FECHA',
        'NOMCC',
        'CONCEPTO',
        'ESTATUS_CXP',
        //'GNOMBRE',
        'FOLIO_FISCAL_ORIG',
        'FECHA',
        'FECHA_FOLIO_FISCAL_ORIG',
        'SERIE',
        'SERIE_FOLIO_FISCAL_ORIG',
        'SUBTOTAL',
        'TOTAL',
        'TIPO_CAMBIO',
        'TIPO_DE_COMPROBANTE',
        'CONDICIONES_DE_PAGO',
        'DESCUENTO',
        'FORMA_DE_PAGO',
        'METODO_DE_PAGO',
        'MONEDA',
        'MONTO_FOLIO_FISCAL_ORIG',
        'LUGAR_EXPEDICION',
        'MOTIVO_DESCUENTO',
        'NO_CERTIFICADO',
        'NUM_CTA_PAGO',
        'NO_CASO',
        'SELLO',
        'VERSION',
        'CERTIFICADO',
        'IDCONCGASTO',
        'ORIGEN',
        'XML',
        'FECHA_CAP',       
        'DESCRIPCION',
        'RFC_EMISOR',
        'RFC_RECEPTOR',
        'NOMBRE_EMISOR',
        'NOMBRE_RECEPTOR',
        'FLAG_POLIZA',
        'RFC_COMPANIA',
        'T_DISTRIBUCION',
        'PRORRATEO',
        'TIPO_CXP',
        'TIPO_GASTO',
        'BENEFICIARIO',
        'OTROS_IMPUESTOS',
        'ESTATUSV',
        'DESCRIPCION_OTRAS',
        'SALDOS_CXP',
        'NUMERO_POL',
        'FECHA_POL',
        'TIPO_POLIZA',
        'FOLIO_PAGOS',
        'NUM_REL_OTRAS',
        'NOM_ESTATUS_CXP'
        

    ]


});

